### ISSUE TITLE
Failed to build the update 0.15.4

### ISSUE THREAD

**Issue by polzak** [JavaEden/OrchidStarter#3]
Hello, thanks for this project.
I tried to clone the newest 0.15.4 version and build without changing anything, but failed.
It was fine yesterday, so I changed plugins and dependencies versions to 0.14.0, and it works fine.
(not exactly fine due to Socket Exception I didn't have yesterday; that's another issue, anyway.)
I am running this on windows 10. 
Let me insert the error message here:

```
1월 26, 2019 3:57:05 오후 org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 6.0.13.Final
[ERROR] Orchid: Something went wrong running Orchid (Unable to provision, see the following errors:

1) Error injecting constructor, org.jruby.exceptions.MainExitException: unknown encoding name - x-windows-949
  at com.eden.orchid.languages.asciidoc.AsciiDoctorCompiler.<init>(AsciiDoctorCompiler.kt:16)
  at com.eden.orchid.languages.asciidoc.AsciiDoctorCompiler.class(AsciiDoctorCompiler.kt:16)
  while locating com.eden.orchid.languages.asciidoc.AsciiDoctorCompiler
  while locating com.eden.orchid.api.compilers.OrchidCompiler annotated with @com.google.inject.internal.Element(setName=,uniqueId=148, type=MULTIBINDER, keyType=)
  while locating java.util.Set<com.eden.orchid.api.compilers.OrchidCompiler>
    for the 1st parameter of com.eden.orchid.api.compilers.CompilerServiceImpl.<init>(CompilerServiceImpl.java:101)
  at com.eden.orchid.api.compilers.CompilerServiceImpl.class(CompilerServiceImpl.java:34)
  while locating com.eden.orchid.api.compilers.CompilerServiceImpl
  while locating com.eden.orchid.api.compilers.CompilerService
    for the 2nd parameter of com.eden.orchid.api.OrchidContextImpl.<init>(OrchidContextImpl.java:52)
  at com.eden.orchid.api.OrchidContextImpl.class(OrchidContextImpl.java:32)
  while locating com.eden.orchid.api.OrchidContextImpl
  while locating com.eden.orchid.api.OrchidContext

1 error)
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, org.jruby.exceptions.MainExitException: unknown encoding name - x-windows-949
  at com.eden.orchid.languages.asciidoc.AsciiDoctorCompiler.<init>(AsciiDoctorCompiler.kt:16)
  at com.eden.orchid.languages.asciidoc.AsciiDoctorCompiler.class(AsciiDoctorCompiler.kt:16)
  while locating com.eden.orchid.languages.asciidoc.AsciiDoctorCompiler
  while locating com.eden.orchid.api.compilers.OrchidCompiler annotated with @com.google.inject.internal.Element(setName=,uniqueId=148, type=MULTIBINDER, keyType=)
  while locating java.util.Set<com.eden.orchid.api.compilers.OrchidCompiler>
    for the 1st parameter of com.eden.orchid.api.compilers.CompilerServiceImpl.<init>(CompilerServiceImpl.java:101)
  at com.eden.orchid.api.compilers.CompilerServiceImpl.class(CompilerServiceImpl.java:34)
  while locating com.eden.orchid.api.compilers.CompilerServiceImpl
  while locating com.eden.orchid.api.compilers.CompilerService
    for the 2nd parameter of com.eden.orchid.api.OrchidContextImpl.<init>(OrchidContextImpl.java:52)
  at com.eden.orchid.api.OrchidContextImpl.class(OrchidContextImpl.java:32)
  while locating com.eden.orchid.api.OrchidContextImpl
  while locating com.eden.orchid.api.OrchidContext

1 error
        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1053)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
        at com.eden.orchid.Orchid.start(Orchid.java:91)
        at com.eden.orchid.Orchid.start(Orchid.java:69)
        at com.eden.orchid.Orchid.main(Orchid.java:60)
Caused by: org.jruby.exceptions.MainExitException: unknown encoding name - x-windows-949
Exception in thread "main" java.lang.NullPointerException
        at com.eden.orchid.Orchid.start(Orchid.java:110)
        at com.eden.orchid.Orchid.start(Orchid.java:69)
        at com.eden.orchid.Orchid.main(Orchid.java:60)

> Task :orchidBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':orchidBuild'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_202\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
3 actionable tasks: 3 executed
```

**Comment by cjbrooks12** [comment]
I think this is an error with the underlying AsciiDoc library. The latest versions of Orchid use Asciidoctorj 1.6, which was a major release. It looks like JRuby doesn't like your machine's default character encoding and I can't see any way to change it on my end. I'll reach out to the Asciidoc team to see what can be done for that.

If you don't want to use AsciiDoc markup, you can just remove the `io.github.javaeden.orchid:OrchidAsciidoc:${orchid_version}` dependency and everything should go on working fine (it's the only plugin that uses JRuby). If you do want to use it, you can set just the `OrchidAsciidoc` dependency back to `0.14.0` and keep the rest at `0.15.4`, I just tested this and it works fine.

**Comment by cjbrooks12** [comment]
I don't think Windows terminals support special UTF-8 characters, which is what the table borders are. I've got a fix in place for using non-special characters for the table borders, will be available in the next release.

For the SocketException, Are you able to navigate those pages regardless of the error, or are pages not loading correctly in Firefox because of it? I can't seem to reproduce it, but I do think I've seen it before. The admin pages create a websocket to receive build progress updates, and I think if you navigate to another page while a message is being received you'll get that error, but it should be safe to ignore. I will look into suppressing those error messages, however.

**Comment by polzak** [comment]
There is no problem navigating pages in Firefox even with the SocketException messages appearing on console. Thanks a lot!
